name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  ci:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: "3.12"

      - name: Install dependencies with uv
        run: |
          uv sync --all-packages

      - name: Run linter python source files
        run: |
          make lint

      - name: Run unit tests
        run: |
          uv run pytest --cov=src --cov-report=xml --cov-report=html --cov-fail-under=0

      - name: Upload coverage report
        uses: codecov/codecov-action@v4
        with:
          files: coverage.xml
          flags: unittests
          token: ${{ secrets.CODECOV_TOKEN }}
